In [14]:
import numpy as np
import pandas as pd
import os
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn import metrics
from sklearn.pipeline import Pipeline

# 使用bag of word

In [15]:

vocab = {}
vocab_word = {}
i = 1
catagory = ["smoking",'smoker','smokes','smoked','smoke','cigarette','cigarettes','cigar','tobacco','tobacco abuse']

path = "train/"
for filename in os.listdir(path):
    
    
    for word in catagory:
        if word in vocab:
            continue
        else:
            vocab[word]=i
            vocab_word[i]=word
            i+=1
    one = [0]*len(vocab)


    with open(os.path.join(path, filename),'r') as txt:

        x = txt.read().lower().split()
        

    for word in x:
        try:
            one[vocab[word]]+=1
        except KeyError:
            continue
    #     one[vocab[word]]+=1


#     print(one)
    print('{0:30} {1}'.format(filename, one))



CURRENT SMOKER_ID_130.txt      [0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_133.txt      [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_223.txt      [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
CURRENT SMOKER_ID_236.txt      [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_241.txt      [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_25.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
CURRENT SMOKER_ID_31.txt       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_43.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_73.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 4]
CURRENT SMOKER_ID_85.txt       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_212.txt          [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
NON-SMOKER_ID_249.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_27.txt           [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
NON-SMOKER_ID_282.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_320.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
NON-SMOKER_ID_331.txt          [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
NON-SMOK

In [16]:
catagory = ["smoking",'smoker','smokes','smoked','smoke','cigarette','cigarettes','cigar','tobacco','tobacco abuse']

path = "train/"
x_train=[]
y_train=[]
for filename in os.listdir(path):
    


    for word in catagory:
        if word in vocab:
            continue
        else:
            vocab[word]=i
            vocab_word[i]=word
            i+=1
    one = [0]*len(vocab)


    with open(os.path.join(path, filename),'r') as txt:

        x = txt.read().lower().split('\n')
        #re.split('\n|.',x)

    for sentance in x:
        words = sentance.split()
        for word in words:
            try:
                one[vocab[word]]+=1
                x_train.append(sentance)
                if re.match("CURRENT SMOKER_ID_\d+.txt", filename):
                    y_train.append(0)
                elif re.match("NON-SMOKER_ID_\d+.txt", filename):
                    y_train.append(1)
                elif re.match("PAST SMOKER_ID_\d+.txt", filename):
                    y_train.append(2)
                elif re.match("UNKNOWN_ID_\d+.txt", filename):
                    y_train.append(3)
                
            except KeyError:
                continue


                


#     print(one)
    print('{0:30} {1}'.format(filename, one))
#print(x_train)
for i in range(len(x_train)):
    print(x_train[i],y_train[i])

CURRENT SMOKER_ID_130.txt      [0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_133.txt      [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_223.txt      [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
CURRENT SMOKER_ID_236.txt      [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_241.txt      [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_25.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
CURRENT SMOKER_ID_31.txt       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_43.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
CURRENT SMOKER_ID_73.txt       [0, 0, 0, 1, 0, 0, 0, 0, 0, 4]
CURRENT SMOKER_ID_85.txt       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_212.txt          [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
NON-SMOKER_ID_249.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_27.txt           [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
NON-SMOKER_ID_282.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
NON-SMOKER_ID_320.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
NON-SMOKER_ID_331.txt          [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
NON-SMOK

# using machine learning 

In [17]:

X_train, X_test, Y_train, Y_test = train_test_split(x_train, y_train, test_size=0.3, random_state=42)

In [18]:

vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train) # remember to use the original X_train set
X_train_tfidf.shape

(25, 132)

In [19]:

clf = LinearSVC()
clf.fit(X_train_tfidf,Y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [20]:

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

# Feed the training data through the pipeline
text_clf.fit(X_train, Y_train)  

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
 ...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [21]:
# Form a prediction set
predictions = text_clf.predict(X_test)

In [22]:

print(metrics.confusion_matrix(Y_test,predictions))

[[5 0 1]
 [0 2 0]
 [0 0 3]]


In [23]:
# Print a classification report
print(metrics.classification_report(Y_test,predictions))

             precision    recall  f1-score   support

          0       1.00      0.83      0.91         6
          1       1.00      1.00      1.00         2
          2       0.75      1.00      0.86         3

avg / total       0.93      0.91      0.91        11



In [24]:
# Print the overall accuracy
print(metrics.accuracy_score(Y_test,predictions))

0.9090909090909091


# input txt file to classify from test file


In [25]:
catagory = ["smoking",'smoker','smokes','smoked','smoke','cigarette','cigarettes','cigar','tobacco','tobacco abuse']

path = "test/"
x_train=[]
file_name = []
one_for_keyword = []
category = []
categroy_temp = 0


for word in catagory:
    if word in vocab:
        continue
    else:
        vocab[word]=i
        vocab_word[i]=word
        i+=1
            
            
for filename in os.listdir(path):
        
    one = [0]*len(vocab)


    with open(os.path.join(path, filename),'r') as txt:

        x = txt.read().lower().split('\n')

    for sentance in x:
        words = sentance.split()
        for word in words:
            try:
                one[vocab[word]]+=1
                x_train.append(sentance)
                categroy_temp = text_clf.predict([sentance])[0]
            except KeyError:
                continue
    
    file_name.append(filename)
    one_for_keyword.append(one)
    
    if one == [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]:
        category.append(3)
    else:
        category.append(categroy_temp)





# predictions = text_clf.predict([x_train[1]])
print('0---current smoker    1---non smoker    2---past smoker    3---unknown\n')
category_print = 0 
for i in range(len(file_name)):

    if category[i] == 0:
        category_print = "current smoker"
    elif category[i] == 1:
        category_print = "non smoker"
    elif category[i]== 2:
        category_print = "past smoker"
    elif category[i] == 3:
        category_print = "unknown"
    print('{0:20} {1} {2}--- {3}'.format(file_name[i], one_for_keyword[i],category[i], category_print ))
    
# for i in range(len(x_train)):    
#     print(x_train[i])


0---current smoker    1---non smoker    2---past smoker    3---unknown

TEST_01.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 1] 2--- past smoker
TEST_02.txt          [0, 0, 1, 0, 0, 0, 1, 0, 0, 0] 0--- current smoker
TEST_03.txt          [0, 3, 0, 0, 0, 0, 0, 0, 0, 0] 2--- past smoker
TEST_04.txt          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0] 2--- past smoker
TEST_05.txt          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0] 0--- current smoker
TEST_06.txt          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0] 1--- non smoker
TEST_07.txt          [0, 0, 1, 0, 0, 0, 0, 1, 0, 0] 0--- current smoker
TEST_08.txt          [0, 0, 1, 0, 0, 0, 0, 0, 0, 0] 1--- non smoker
TEST_09.txt          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 3--- unknown
TEST_10.txt          [0, 0, 0, 0, 0, 1, 0, 0, 0, 0] 1--- non smoker
TEST_11.txt          [0, 2, 0, 0, 0, 0, 0, 0, 0, 0] 2--- past smoker
TEST_12.txt          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0] 0--- current smoker
TEST_13.txt          [0, 1, 0, 0, 0, 0, 0, 1, 0, 0] 0--- current smoker
TEST_14.txt          [0